-- Photon Fury MISC
begin;create table if not exists public.player_photon_fury(user_id uuid primary key references public.player_stats(user_id)on delete cascade,unlocked_at timestamptz,photons int8 not null default 0 check(photons>=0));
alter table public.player_photon_fury enable row level security;revoke all on public.player_photon_fury from public,anon,authenticated;grant select on public.player_photon_fury to authenticated;drop policy if exists photon_own_read on public.player_photon_fury;create policy photon_own_read on public.player_photon_fury for select to authenticated using(user_id=auth.uid());create table if not exists app_private.photon_fury_runs(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.player_stats(user_id)on delete cascade,started_at timestamptz not null default clock_timestamp(),finished_at timestamptz,active_seconds numeric,reflections int,awarded int8);create index if not exists photon_runs_user on app_private.photon_fury_runs(user_id,started_at);revoke all on app_private.photon_fury_runs from public,anon,authenticated;
create or replace function app_private.photon_user()returns uuid language plpgsql security definer set search_path='' as $$declare u uuid:=auth.uid();begin if u is null then raise exception 'Sign in required';end if;if app_private.has_active_ban(u,'account',null)then raise exception 'Account banned';end if;return u;end$$;revoke all on function app_private.photon_user()from public,anon,authenticated;
create or replace function public.unlock_photon_fury()returns jsonb language plpgsql security definer set search_path='' as $$declare u uuid:=app_private.photon_user();s public.player_stats;p public.player_photon_fury;begin select*into s from public.player_stats where user_id=u for update;insert into public.player_photon_fury(user_id)values(u)on conflict do nothing;select*into p from public.player_photon_fury where user_id=u for update;if p.unlocked_at is null then if coalesce(s.level,0)<15 then raise exception 'Requires level 15';end if;if coalesce(s.total_gems,0)<100 then raise exception 'You need 100 Gems';end if;update public.player_stats set total_gems=total_gems-100,updated_at=clock_timestamp()where user_id=u returning*into s;update public.player_photon_fury set unlocked_at=clock_timestamp()where user_id=u;end if;return jsonb_build_object('unlocked',true,'total_gems',s.total_gems);end$$;
create or replace function public.begin_photon_fury_run()returns jsonb language plpgsql security definer set search_path='' as $$declare u uuid:=app_private.photon_user();r uuid;begin if not exists(select 1 from public.player_photon_fury where user_id=u and unlocked_at is not null)then raise exception 'Mode locked';end if;perform pg_advisory_xact_lock(hashtextextended(u::text,803100));if exists(select 1 from app_private.photon_fury_runs where user_id=u and started_at>clock_timestamp()-interval '1s')then raise exception 'Wait 1s';end if;if app_private.is_admin_test_user(u)then raise exception 'Test run';end if;update app_private.photon_fury_runs set finished_at=clock_timestamp(),active_seconds=0,reflections=0,awarded=0 where user_id=u and finished_at is null;insert into app_private.photon_fury_runs(user_id)values(u)returning id into r;return jsonb_build_object('run_id',r);end$$;
alter table public.player_photon_fury add column if not exists selected_character_key text not null default 'photon_magician';
create or replace function app_private.photon_character_rules(p_key text)returns table(character_key text,max_hp numeric,durability int,guard_seconds numeric,cooldown_seconds numeric,bonus_point_seconds int,heal_amount numeric,heal_cooldown_seconds numeric)language sql immutable set search_path='' as $$select*from(values('photon_magician',4.,7,.4,1.5,40,0.,0.),
('photon_tick',4,7,.5,1.2,null,0,0),
('photon_trumpet',5,12,.4,1.2,null,0,0),
('photon_saxophone',4,5,.4,.2,null,.5,25),
('photon_wizard',4,7,.4,1.5,null,0,0),
('photon_burner',4,7,.3,2,null,0,0),
('photon_bluff',5,7,.3,1.5,null,0,0),
('photon_magnet',4,7,.4,1.5,null,0,0),
('photon_bear',4,7,.4,1.5,null,0,0),
('photon_wrench',4,7,.9,3.5,null,0,0))c where p_key is null or c.column1=p_key;$$;revoke all on function app_private.photon_character_rules(text)from public,anon,authenticated;
alter table app_private.photon_fury_runs add column if not exists character_key text,add column if not exists saber_cooldown_seconds numeric not null default .6,add column if not exists bonus_point_seconds int,add column if not exists point_multiplier numeric not null default 1,add column if not exists extra_points int not null default 0;
create or replace function public.get_photon_fury_profile()returns jsonb language sql security definer set search_path='' as $$select jsonb_build_object('unlocked',p.unlocked_at is not null,'photons',coalesce(p.photons,0),'character_keys',(select coalesce(jsonb_agg(character_key),'[]'::jsonb)from app_private.photon_character_rules(null)where p.unlocked_at is not null),'selected_character_key',p.selected_character_key)from app_private.photon_user()u left join public.player_photon_fury p on p.user_id=u;$$;
create or replace function public.equip_photon_character(p_character_key text)returns jsonb language plpgsql security definer set search_path='' as $$declare k text:=p_character_key;u uuid:=app_private.photon_user();begin perform 1 from app_private.photon_character_rules(k)where k is not null;if not found then raise exception 'Invalid character';end if;update public.player_photon_fury set selected_character_key=k where user_id=u and unlocked_at is not null;if not found then raise exception 'Mode locked';end if;return public.get_photon_fury_profile();end$$;
create or replace function public.begin_photon_character_run(p_character_key text)returns jsonb language plpgsql security definer set search_path='' as $$declare k text:=p_character_key;u uuid:=auth.uid();c record;p jsonb;begin select*into c from app_private.photon_character_rules(k);if c.character_key is null or k is null then raise exception 'Invalid character';end if;p:=public.begin_photon_fury_run();update app_private.photon_fury_runs set character_key=c.character_key,saber_cooldown_seconds=c.cooldown_seconds,bonus_point_seconds=c.bonus_point_seconds,point_multiplier=case when k='photon_burner'then 2 else 1 end where id=(p->>'run_id')::uuid and user_id=u;return p||jsonb_build_object('character_key',c.character_key);end$$;
create or replace function public.finish_photon_character_run(p_run_id uuid,p_active_seconds numeric,p_reflections int,p_extra_points int)returns jsonb language plpgsql security definer set search_path='' as $$declare t numeric:=p_active_seconds;n int:=p_reflections;x int:=p_extra_points;u uuid:=app_private.photon_user();r app_private.photon_fury_runs;v int8;b int8;s numeric;h numeric;l numeric;begin select*into r from app_private.photon_fury_runs where id=$1 and user_id=u for update;if r.id is null then raise exception 'No run';end if;if r.finished_at is not null then select photons into b from public.player_photon_fury where user_id=u;return jsonb_build_object('awarded',r.awarded,'photons',b);end if;if not coalesce(t between 0 and 21600,false)or t>extract(epoch from clock_timestamp()-r.started_at)+.5 then raise exception 'Invalid playtime';end if;if n is null or n<0 or n>floor(t/r.saber_cooldown_seconds)+1 then raise exception 'Invalid reflections';end if;if app_private.is_admin_test_user(u)then raise exception 'Test run';end if;h:=least(1e6,ceil((power(1.004,t/2)-1)*772)+3);l:=case r.character_key when 'photon_magnet' then 3*h when 'photon_bear' then 2*n+h when 'photon_wrench' then n else 0 end;if x is null or x<0 or x>l or(r.character_key='photon_magnet' and x%3<>0)then raise exception 'Invalid bonus';end if;s:=n*r.point_multiplier+x+coalesce(floor(t/nullif(r.bonus_point_seconds,0)),0);v:=case when s>=4 then ((s-4)^2+1)::int8 else 0 end;update public.player_photon_fury set photons=photons+v where user_id=u and unlocked_at is not null returning photons into b;if b is null then raise exception 'Mode locked';end if;update app_private.photon_fury_runs set finished_at=clock_timestamp(),active_seconds=t,reflections=n,extra_points=x,awarded=v where id=r.id;return jsonb_build_object('awarded',v,'photons',b,'points',s);end$$;
create or replace function public.finish_photon_fury_run(p_run_id uuid,p_active_seconds numeric,p_reflections int)returns jsonb language sql security definer set search_path='' as $$select public.finish_photon_character_run($1,$2,$3,0);$$;do $$ declare f text;begin foreach f in array array['get_photon_fury_profile()','unlock_photon_fury()','begin_photon_fury_run()','finish_photon_fury_run(uuid,numeric,int)','equip_photon_character(text)','begin_photon_character_run(text)','finish_photon_character_run(uuid,numeric,int,int)']loop execute format('revoke all on function public.%s from public,anon;grant execute on function public.%s to authenticated',f,f);end loop;end$$;
notify pgrst,'reload schema';commit;
