'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
type Kind='coin'|'car'|'log'|'rock'|'heart'; type Item={id:number;lane:number;y:number;kind:Kind};
function Obstacle({kind}:{kind:Kind}){
 if(kind==='coin'||kind==='heart')return <span>{kind==='coin'?'●':'♥'}</span>;
 if(kind==='car')return <div className="car-shape"><i className="windshield"/><i className="light left"/><i className="light right"/><i className="wheel left"/><i className="wheel right"/><b/></div>;
 if(kind==='log')return <div className="log-shape"><i/><b/><em/></div>;
 return <div className="rock-shape"><i/><b/><em/></div>;
}
export default function Home(){
 const [lane,setLane]=useState(2),[items,setItems]=useState<Item[]>([]),[score,setScore]=useState(0),[coins,setCoins]=useState(0),[hearts,setHearts]=useState(3),[wave,setWave]=useState(1),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[over,setOver]=useState(false),[flash,setFlash]=useState('');
 const id=useRef(0),last=useRef(0),state=useRef({lane,running,paused}); state.current={lane,running,paused};
 const reset=useCallback(()=>{setLane(2);setItems([]);setScore(0);setCoins(0);setHearts(3);setWave(1);setOver(false);setPaused(false);setRunning(true);last.current=0},[]);
 const move=useCallback((d:number)=>{if(state.current.running&&!state.current.paused)setLane(v=>Math.max(0,Math.min(4,v+d)))},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(['ArrowLeft','a','A'].includes(e.key)){e.preventDefault();move(-1)}if(['ArrowRight','d','D'].includes(e.key)){e.preventDefault();move(1)}if(e.key===' '&&state.current.running){e.preventDefault();setPaused(v=>!v)}if(e.key==='Enter'&&!state.current.running)reset()};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[move,reset]);
 useEffect(()=>{if(!running||paused)return;let raf=0,prev=performance.now();const tick=(now:number)=>{const dt=Math.min(32,now-prev);prev=now;if(now-last.current>Math.max(330,980-wave*55)){last.current=now;const r=Math.random(),danger=Math.min(.79,.54+wave*.025);const kind:Kind=r<danger?(['car','log','rock']as Kind[])[Math.floor(Math.random()*3)]:r>.975?'heart':'coin';setItems(v=>[...v,{id:id.current++,lane:Math.floor(Math.random()*5),y:-10,kind}])}setItems(old=>old.flatMap(item=>{const n={...item,y:item.y+(.02+wave*.0026)*dt};if(n.lane===state.current.lane&&n.y>78&&n.y<93){if(n.kind==='coin'){setCoins(v=>v+1);setScore(v=>v+100);setFlash('coin')}else if(n.kind==='heart'){setHearts(v=>Math.min(3,v+1));setFlash('coin')}else{setHearts(v=>{const h=v-1;if(h<=0){setRunning(false);setOver(true)}return Math.max(0,h)});setFlash('hit')}setTimeout(()=>setFlash(''),180);return[]}return n.y<108?[n]:[]}));setScore(v=>v+Math.max(1,Math.round(dt/12)));raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[running,paused,wave]);
 useEffect(()=>{if(running)setWave(Math.floor(score/1500)+1)},[score,running]);
 return <main className={`game-shell ${flash}`}><section className="game-card" aria-label="Skyway Sprint runner game"><header className="topbar"><div className="brand"><span>S</span><div><b>SKYWAY</b><small>SPRINT</small></div></div><div className="stats"><div><small>SCORE</small><strong>{score.toString().padStart(6,'0')}</strong></div><div><small>COINS</small><strong className="gold">● {coins}</strong></div><div><small>WAVE</small><strong>{wave}</strong></div></div><div className="health" aria-label={`${hearts} hearts`}>{[0,1,2].map(n=><span key={n} className={n<hearts?'':'lost'}>♥</span>)}</div></header><div className="playfield"><div className="sky"><i/><i/><i/></div><div className="horizon">{[0,1,2,3,4].map(n=><span key={n}/>)}</div><div className="road">{[0,1,2,3].map(n=><i className={`line l${n}`} key={n}/>)}<div className="wave-chip">WAVE {wave}<small>SPEED ×{(1+(wave-1)*.12).toFixed(2)}</small></div>{items.map(x=><div key={x.id} className={`item ${x.kind}`} style={{left:`${(x.lane+.5)*20}%`,top:`${x.y}%`}} aria-label={x.kind}><Obstacle kind={x.kind}/></div>)}<div className="runner" style={{left:`${(lane+.5)*20}%`}}><div className="head"/><div className="body"/><i className="arm a1"/><i className="arm a2"/><i className="leg g1"/><i className="leg g2"/><em/></div></div>{!running&&<div className="overlay"><p>{over?'RUN OVER':'FIVE LANES. NO BRAKES.'}</p><h1>{over?`${score.toLocaleString()} POINTS`:'DODGE. DASH. SURVIVE.'}</h1><button onClick={reset}>{over?'RUN AGAIN':'START RUN'} <span>→</span></button><small>← → / A D &nbsp; TO SWITCH LANES</small></div>}{paused&&<div className="overlay compact"><h1>PAUSED</h1><button onClick={()=>setPaused(false)}>KEEP RUNNING</button></div>}</div><footer><button onClick={()=>move(-1)} aria-label="Move left">←</button><p><b>SWITCH LANES</b><small>Use arrows, A / D, or tap</small></p><button onClick={()=>move(1)} aria-label="Move right">→</button><button className="pause" onClick={()=>running&&setPaused(v=>!v)} aria-label="Pause">{paused?'▶':'Ⅱ'}</button></footer></section></main>
}
